// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBifS75sFOgqWliNwx7bUIWCJWzA8AlgCQ',
    appId: '1:218171195114:web:940753b40eef45f338a193',
    messagingSenderId: '218171195114',
    projectId: 'greenmetrics-dev',
    authDomain: 'greenmetrics-dev.firebaseapp.com',
    storageBucket: 'greenmetrics-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG4gRi9v8md7Sapvp0YUWiXOSFfQ9OuAY',
    appId: '1:218171195114:android:6c34d55b3dc1030838a193',
    messagingSenderId: '218171195114',
    projectId: 'greenmetrics-dev',
    storageBucket: 'greenmetrics-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUtSDWVXp1CKpT2970tss_5B7kluz2low',
    appId: '1:218171195114:ios:2a9a1f87e5d41ace38a193',
    messagingSenderId: '218171195114',
    projectId: 'greenmetrics-dev',
    storageBucket: 'greenmetrics-dev.appspot.com',
    iosBundleId: 'com.example.secureFlutterChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUtSDWVXp1CKpT2970tss_5B7kluz2low',
    appId: '1:218171195114:ios:2a9a1f87e5d41ace38a193',
    messagingSenderId: '218171195114',
    projectId: 'greenmetrics-dev',
    storageBucket: 'greenmetrics-dev.appspot.com',
    iosBundleId: 'com.example.secureFlutterChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBifS75sFOgqWliNwx7bUIWCJWzA8AlgCQ',
    appId: '1:218171195114:web:e33e8b79cb2489d838a193',
    messagingSenderId: '218171195114',
    projectId: 'greenmetrics-dev',
    authDomain: 'greenmetrics-dev.firebaseapp.com',
    storageBucket: 'greenmetrics-dev.appspot.com',
  );

}