// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtWfXgyBcmrSPznbunWHX97mlPD2Ij9PA',
    appId: '1:879426475852:web:4da3f4d216f7c24b0561e9',
    messagingSenderId: '879426475852',
    projectId: 'privychat-4bc01',
    authDomain: 'privychat-4bc01.firebaseapp.com',
    storageBucket: 'privychat-4bc01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR2MrzDk9LlJQkuadlw_uBqYTVZ-0FfXI',
    appId: '1:879426475852:android:e49d67a9eda190bc0561e9',
    messagingSenderId: '879426475852',
    projectId: 'privychat-4bc01',
    storageBucket: 'privychat-4bc01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOoCMArZvDMMXKZPzKKLjSoDRiTw4bCGs',
    appId: '1:879426475852:ios:b504fec99543b4560561e9',
    messagingSenderId: '879426475852',
    projectId: 'privychat-4bc01',
    storageBucket: 'privychat-4bc01.appspot.com',
    iosBundleId: 'com.example.privyChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOoCMArZvDMMXKZPzKKLjSoDRiTw4bCGs',
    appId: '1:879426475852:ios:b504fec99543b4560561e9',
    messagingSenderId: '879426475852',
    projectId: 'privychat-4bc01',
    storageBucket: 'privychat-4bc01.appspot.com',
    iosBundleId: 'com.example.privyChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtWfXgyBcmrSPznbunWHX97mlPD2Ij9PA',
    appId: '1:879426475852:web:ec7036c41284e5ea0561e9',
    messagingSenderId: '879426475852',
    projectId: 'privychat-4bc01',
    authDomain: 'privychat-4bc01.firebaseapp.com',
    storageBucket: 'privychat-4bc01.appspot.com',
  );
}
