name: Build & Upload to Firebase App Distribution

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Decode google-services.json
        env: 
            GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json

      - name: Decode firebase_option
        env:
          firebase_options_dart: ${{ secrets.FIREBASE_OPTION }}
        run: echo "$firebase_options_dart" > lib/firebase_options.dart

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      
      - run: flutter pub get
      
      # Build Android APK
      - run: flutter build apk
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
      
      # Build iOS App
      - name: Set up Xcode
        uses: apple-actions/setup-xcode@v3
        with:
          xcode-version: '14.x' # specify the version that matches your project

      - name: Build iOS app
        run: |
          flutter build ios --release --no-codesign
        env:
          FLUTTER_BUILD_MODE: release

      - name: Upload iOS build artifact
        uses: actions/upload-artifact@v1
        with:
          name: release-ios
          path: build/ios/iphoneos/Runner.app

      # Upload APK to Firebase App Distribution
      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
            appId: ${{ secrets.PRIVY_CHAT_ID_ANDROID }}
            token: ${{ secrets.TOKEN }}
            groups: testing_group
            file: build/app/outputs/apk/release/app-release.apk

      # Upload iOS IPA to Firebase App Distribution
      - name: Upload IPA to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
            appId: ${{ secrets.PRIVY_CHAT_ID_IOS }}
            token: ${{ secrets.TOKEN }}
            groups: testing_group
            file: build/ios/iphoneos/Runner.ipa
