name: Build & Upload to Firebase App Distribution

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: macos-latest # Use macOS runner for iOS builds

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Decode google-services.json
        env: 
            GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json

      - name: Decode firebase_option
        env:
          firebase_options_dart: ${{ secrets.FIREBASE_OPTION }}
        run: echo "$firebase_options_dart" > lib/firebase_options.dart

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      
      - run: flutter pub get
      
      # Build Android APK
      - run: flutter build apk
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
      
      # Build iOS App
      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Build iOS app
        run: |
          flutter build ios --release --no-codesign
          # Archive the build
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration AppStoreDistribution archive -archivePath ${{ runner.temp }}/Runner.xcarchive
          # Export the IPA
          xcodebuild -exportArchive -archivePath ${{ runner.temp }}/Runner.xcarchive -exportOptionsPlist ios/ExportOptions.plist -exportPath ${{ runner.temp }}/

      - name: Upload iOS build artifact
        uses: actions/upload-artifact@v1
        with:
          name: release-ios
          path: ${{ runner.temp }}/Runner.ipa

      # Upload APK to Firebase App Distribution
      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
            appId: ${{ secrets.PRIVY_CHAT_ID }}
            token: ${{ secrets.TOKEN }}
            groups: testing_group
            file: build/app/outputs/apk/release/app-release.apk

      # Upload iOS IPA to Firebase App Distribution
      - name: Upload IPA to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
            appId: ${{ secrets.PRIVY_CHAT_ID }}
            token: ${{ secrets.TOKEN }}
            groups: testing_group
            file: ${{ runner.temp }}/Runner.ipa
